CREATE TABLE IF NOT EXISTS formulare_refi_rates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bank VARCHAR(100) NOT NULL,
  fixation VARCHAR(20) NOT NULL,
  rate DECIMAL(4,2) NOT NULL,
  note VARCHAR(255) NOT NULL DEFAULT '',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
